(ns gc-api-browser.json-schema-fixture)

(def fixture
  {:description        "GoCardless Pro API",
   :properties         {:creditor              {:$ref "#/definitions/creditor"},
                        :creditor_bank_account {:$ref "#/definitions/creditor_bank_account"}},
   :definitions        {:creditor {:$schema     "https://developer.gocardless.com/hyper-schema.json",
                                   :title       "Creditors",
                                   :envelope    "creditors",
                                   :description "Each [payment](#core-endpoints-payments) taken through the API is linked to a \"creditor\", to whom the payment is then paid out. In most cases your organisation will have a single \"creditor\", but the API also supports collecting payments on behalf of others.\n\nPlease get in touch if you wish to use this endpoint. Currently, for Anti Money Laundering reasons, any creditors you add must be directly related to your organisation.",
                                   :definitions {:postal_code              {:description "The creditor's postal code.",
                                                                            :example     "EC1V 7LQ",
                                                                            :type        ["string" "null"]},
                                                 :identity                 {:$ref "#/definitions/creditor/definitions/id"},
                                                 :name                     {:description "The creditor's name.",
                                                                            :example     "Nude Wines",
                                                                            :type        ["string"]},
                                                 :city                     {:description "The city of the creditor's address.",
                                                                            :example     "London",
                                                                            :type        ["string" "null"]},
                                                 :multi_resource_response  {:type                 ["object"],
                                                                            :description          "",
                                                                            :properties           {:creditors {:type  ["array"]
                                                                                                               :items {:$ref "#/definitions/creditor"}},
                                                                                                   :meta      {:$ref "#/definitions/customer/definitions/list_meta"}},
                                                                            :additionalProperties false},
                                                 :region                   {:description "The creditor's address region, county or department.",
                                                                            :example     nil,
                                                                            :type        ["string" "null"]},
                                                 :address_line2            {:description "The second line of the creditor's address.",
                                                                            :example     "Islington",
                                                                            :type        ["string" "null"]},
                                                 :country_code             {:description
                                                                                     "[ISO 3166-1](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) alpha-2 code, currently only \"GB\" is supported.",
                                                                            :example "GB",
                                                                            :type    ["string" "null"]},
                                                 :single_resource_response {:type                 ["object"],
                                                                            :description          "",
                                                                            :properties           {:creditors {:$ref "#/definitions/creditor"}},
                                                                            :additionalProperties false},
                                                 :id                       {:description "Unique identifier, beginning with \"CR\".",
                                                                            :example     "CR123",
                                                                            :type        ["string"]},
                                                 :address_line3            {:description "The third line of the creditor's address.",
                                                                            :example     nil,
                                                                            :type        ["string" "null"]},
                                                 :address_line1            {:description "The first line of the creditor's address.",
                                                                            :example     "338-346 Goswell Road",
                                                                            :type        ["string" "null"]},
                                                 :created_at               {:description
                                                                                     "Fixed [timestamp](#overview-time-zones-dates), recording when this resource was created.",
                                                                            :example "2014-01-01T12:00:00.000Z",
                                                                            :format  "date-time",
                                                                            :type    ["string"]},
                                                 :links                    {:description "",
                                                                            :type        ["object"],
                                                                            :properties  {:default_gbp_payout_account {:description "ID of the [bank account](#whitelabel-partner-endpoints-creditor-bank-accounts) which is set up to receive payouts in GBP.",
                                                                                                                       :example     "BA123",
                                                                                                                       :type        ["string" "null"]},
                                                                                          :default_eur_payout_account {:description "ID of the [bank account](#whitelabel-partner-endpoints-creditor-bank-accounts) which is set up to receive payouts in EUR.",
                                                                                                                       :example     "BA456",
                                                                                                                       :type        ["string" "null"]}}}},
                                   :links       [{:rel          "create",
                                                  :description  "Creates a new creditor.",
                                                  :schema       {:type                 ["object"],
                                                                 :properties           {:postal_code   {:$ref "#/definitions/creditor/definitions/postal_code"},
                                                                                        :name          {:$ref "#/definitions/creditor/definitions/name"},
                                                                                        :city          {:$ref "#/definitions/creditor/definitions/city"},
                                                                                        :region        {:$ref "#/definitions/creditor/definitions/region"},
                                                                                        :address_line2 {:$ref "#/definitions/creditor/definitions/address_line2"},
                                                                                        :country_code  {:$ref "#/definitions/creditor/definitions/country_code"},
                                                                                        :address_line3 {:$ref "#/definitions/creditor/definitions/address_line3"},
                                                                                        :address_line1 {:$ref "#/definitions/creditor/definitions/address_line1"},
                                                                                        :links         {:description          "",
                                                                                                        :type                 ["object"],
                                                                                                        :properties           {},
                                                                                                        :additionalProperties false}},
                                                                 :required             ["name" "address_line1" "city" "postal_code" "country_code"],
                                                                 :additionalProperties false},
                                                  :method       "POST",
                                                  :title        "Create a creditor",
                                                  :notes        {:restricted "this endpoint is [restricted](#overview-restrictions) to accounts which have been approved as whitelabel partners. Please contact support if you're interested in managing multiple creditors."},
                                                  :example      "POST https://api.gocardless.com/creditors HTTP/1.1\n{\n  \"creditors\": {\n    \"name\": \"The Wine Club\",\n    \"address_line1\": \"9 Acer Gardens\",\n    \"city\": \"Birmingham\",\n    \"postal_code\": \"B4 7NJ\",\n    \"country_code\": \"GB\"\n  }\n}\n\nHTTP/1.1 201 (Created)\nLocation: /creditors/CR123\n{\n  \"creditors\": {\n    \"id\": \"CR123\",\n    \"created_at\": \"2014-05-27T12:43:17.000Z\",\n    \"name\": \"The Wine Club\",\n    \"address_line1\": \"9 Acer Gardens\",\n    \"address_line2\": null,\n    \"address_line3\": null,\n    \"city\": \"Birmingham\",\n    \"region\": null,\n    \"postal_code\": \"B4 7NJ\",\n    \"country_code\": \"GB\"\n  }\n}\n",
                                                  :targetSchema {:$ref "#/definitions/creditor/definitions/single_resource_response"},
                                                  :href         "/creditors"}
                                                 {:title        "List creditors",
                                                  :description  "Returns a [cursor-paginated](#overview-cursor-pagination) list of your creditors.",
                                                  :href         "/creditors",
                                                  :method       "GET",
                                                  :rel          "instances",
                                                  :schema       {:type                 ["object"],
                                                                 :properties           {:after  {:type        ["string"],
                                                                                                 :description "Cursor pointing to the start of the desired set."},
                                                                                        :before {:type        ["string"],
                                                                                                 :description "Cursor pointing to the end of the desired set."},
                                                                                        :limit  {:type        ["integer" "string"],
                                                                                                 :description "Number of records to return."}},
                                                                 :additionalProperties false},
                                                  :targetSchema {:$ref "#/definitions/creditor/definitions/multi_resource_response"},
                                                  :example      "GET https://api.gocardless.com/creditors HTTP/1.1\n\nHTTP/1.1 200 (OK)\n{\n  \"meta\": {\n    \"cursors\": {\n      \"before\": null,\n      \"after\": \"CR123\",\n    },\n    \"limit\": 50\n  },\n  \"creditors\":[{\n    \"id\": \"CR123\",\n    \"created_at\": \"2014-05-27T12:43:17.000Z\",\n    \"name\": \"The Wine Club\",\n    \"address_line1\": \"9 Acer Gardens\",\n    \"address_line2\": null,\n    \"address_line3\": null,\n    \"city\": \"Birmingham\",\n    \"region\": null,\n    \"postal_code\": \"B4 7NJ\",\n    \"country_code\": \"GB\",\n    \"links\": {\n      \"default_gbp_payout_account\": \"BA123\"\n    }\n  }, {\n  ...\n  }]\n}\n"}
                                                 {:title        "Get a single creditor",
                                                  :description  "Retrieves the details of an existing creditor.",
                                                  :href         "/creditors/{(%23%2Fdefinitions%2Fcreditor%2Fdefinitions%2Fidentity)}",
                                                  :method       "GET",
                                                  :rel          "self",
                                                  :targetSchema {:$ref "#/definitions/creditor/definitions/single_resource_response"},
                                                  :example      "GET https://api.gocardless.com/creditors/CR123 HTTP/1.1\n\nHTTP/1.1 200 (OK)\n{\n  \"creditors\": {\n    \"id\": \"CR123\",\n    \"created_at\": \"2014-05-27T12:43:17.000Z\",\n    \"name\": \"The Wine Club\",\n    \"address_line1\": \"9 Acer Gardens\",\n    \"address_line2\": null,\n    \"address_line3\": null,\n    \"city\": \"Birmingham\",\n    \"region\": null,\n    \"postal_code\": \"B4 7NJ\",\n    \"country_code\": \"GB\",\n    \"links\": {\n      \"default_gbp_payout_account\": \"BA123\"\n    }\n  }\n}\n"}
                                                 {:title        "Update a creditor",
                                                  :description  "Updates a creditor object. Supports all of the fields supported when creating a creditor.",
                                                  :href         "/creditors/{(%23%2Fdefinitions%2Fcreditor%2Fdefinitions%2Fidentity)}",
                                                  :method       "PUT",
                                                  :rel          "update",
                                                  :schema       {:type                 ["object"],
                                                                 :properties           {:postal_code   {:$ref "#/definitions/creditor/definitions/postal_code"},
                                                                                        :name          {:$ref "#/definitions/creditor/definitions/name"},
                                                                                        :city          {:$ref "#/definitions/creditor/definitions/city"},
                                                                                        :region        {:$ref "#/definitions/creditor/definitions/region"},
                                                                                        :address_line2 {:$ref "#/definitions/creditor/definitions/address_line2"},
                                                                                        :country_code  {:$ref "#/definitions/creditor/definitions/country_code"},
                                                                                        :address_line3 {:$ref "#/definitions/creditor/definitions/address_line3"},
                                                                                        :address_line1 {:$ref "#/definitions/creditor/definitions/address_line1"},
                                                                                        :links         {:$ref "#/definitions/creditor/definitions/links"}},
                                                                 :additionalProperties false},
                                                  :targetSchema {:$ref "#/definitions/creditor/definitions/single_resource_response"},
                                                  :example      "PUT https://api.gocardless.com/creditors/CR123 HTTP/1.1\n{\n  \"creditors\": {\n    \"name\": \"Nude Wines\",\n    \"links\": {\n      \"default_gbp_payout_account\": \"BA789\"\n    }\n  }\n}\n\nHTTP/1.1 200 (OK)\n{\n  \"creditors\": {\n    \"id\": \"CR123\",\n    \"created_at\": \"2014-05-27T12:43:17.000Z\",\n    \"name\": \"Nude Wines\",\n    \"address_line1\": \"9 Acer Gardens\",\n    \"address_line2\": null,\n    \"address_line3\": null,\n    \"city\": \"Birmingham\",\n    \"region\": null,\n    \"postal_code\": \"B4 7NJ\",\n    \"country_code\": \"GB\",\n    \"links\": {\n      \"default_gbp_payout_account\": \"BA789\"\n    }\n  }\n}\n"}],
                                   :properties  {:postal_code   {:$ref "#/definitions/creditor/definitions/postal_code"},
                                                 :name          {:$ref "#/definitions/creditor/definitions/name"},
                                                 :city          {:$ref "#/definitions/creditor/definitions/city"},
                                                 :region        {:$ref "#/definitions/creditor/definitions/region"},
                                                 :address_line2 {:$ref "#/definitions/creditor/definitions/address_line2"},
                                                 :country_code  {:$ref "#/definitions/creditor/definitions/country_code"},
                                                 :id            {:$ref "#/definitions/creditor/definitions/id"},
                                                 :address_line3 {:$ref "#/definitions/creditor/definitions/address_line3"},
                                                 :address_line1 {:$ref "#/definitions/creditor/definitions/address_line1"},
                                                 :created_at    {:$ref "#/definitions/creditor/definitions/created_at"},
                                                 :links         {:$ref "#/definitions/creditor/definitions/links"}},
                                   :type        ["object"]},,
                        :creditor_bank_account
                                  {:$schema     "https://developer.gocardless.com/hyper-schema.json",
                                   :title       "Creditor Bank Accounts",
                                   :envelope    "creditor_bank_accounts",
                                   :description "Creditor Bank Accounts hold the bank details of a [creditor](#whitelabel-partner-endpoints-creditors). These are the bank accounts which your [payouts](#core-endpoints-payouts) will be sent to.\n\nNote that creditor bank accounts must be unique, and so you will encounter a `bank_account_exists` error if you try to create a duplicate bank account. You may wish to handle this by updating the existing record instead, the ID of which will be provided as `links[creditor_bank_account]` in the error response.",
                                   :definitions {:identity                      {:$ref "#/definitions/creditor_bank_account/definitions/id"},
                                                 :branch_code                   {:description "Branch code - see [local details](#ui-local-bank-details) for more information. Alternatively you can provide an `iban`.",
                                                                                 :example     "20-00-00",
                                                                                 :type        ["string" "null"]},
                                                 :bank_name                     {:description "Name of bank, taken from sort code.",
                                                                                 :example     "BARCLAYS BANK PLC",
                                                                                 :type        ["string"]},
                                                 :multi_resource_response       {:type                 ["object"],
                                                                                 :description          "",
                                                                                 :properties           {:creditor_bank_accounts {:type  ["array"]
                                                                                                                                 :items {:$ref "#/definitions/creditor_bank_account"}},
                                                                                                        :meta                   {:$ref "#/definitions/customer/definitions/list_meta"}},
                                                                                 :additionalProperties false},
                                                 :currency                      {:description "[ISO 4217](http://en.wikipedia.org/wiki/ISO_4217#Active_codes) currency code, defaults to national currency of `country_code`.",
                                                                                 :example     "GBP",
                                                                                 :type        ["string" "null"]},
                                                 :country_code                  {:description "[ISO 3166-1](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) alpha-2 code. Defaults to the country code of the `iban` if supplied, otherwise is required.",
                                                                                 :example     "GB",
                                                                                 :type        ["string" "null"]},
                                                 :bank_code                     {:description "Bank code - see [local details](#ui-local-bank-details) for more information. Alternatively you can provide an `iban`.",
                                                                                 :example     nil,
                                                                                 :type        ["string" "null"]},
                                                 :single_resource_response      {:type                 ["object"],
                                                                                 :description          "",
                                                                                 :properties           {:creditor_bank_accounts {:$ref "#/definitions/creditor_bank_account"}},
                                                                                 :additionalProperties false},
                                                 :account_number                {:description "Bank account number - see [local details](#ui-local-bank-details) for more information. Alternatively you can provide an `iban`.",
                                                                                 :example     "55779911",
                                                                                 :type        ["string" "null"]},
                                                 :id                            {:description "Unique identifier, beginning with \"BA\".",
                                                                                 :example     "BA123",
                                                                                 :type        ["string"]},
                                                 :account_holder_name           {:description "Name of the account holder, as known by the bank. Usually this is the same as the name stored with the linked [creditor](#whitelabel-partner-endpoints-creditors). This field will be transliterated, upcased and truncated to 18 characters.",
                                                                                 :example     "Nude Wines",
                                                                                 :type        ["string"]},
                                                 :account_number_ending         {:description "Last two digits of account number.",
                                                                                 :example     "11",
                                                                                 :type        ["string"]},
                                                 :iban                          {:description "International Bank Account Number. Alternatively you can provide [local details](#ui-local-bank-details).",
                                                                                 :example     "GB60BARC20000055779911",
                                                                                 :type        ["string" "null"]},
                                                 :set_as_default_payout_account {:description
                                                                                       "Defaults to `false`. When this is set to `true`, it will cause this bank account to be set as the account that GoCardless will pay out to.",
                                                                                 :type ["boolean"]},
                                                 :enabled                       {:description "Boolean value showing whether the bank account is enabled or disabled.",
                                                                                 :example     true,
                                                                                 :type        ["boolean"]},
                                                 :created_at                    {:description "Fixed [timestamp](#overview-time-zones-dates), recording when this resource was created.",
                                                                                 :example     "2014-01-01T12:00:00.000Z",
                                                                                 :format      "date-time",
                                                                                 :type        ["string"]},
                                                 :links                         {:description "",
                                                                                 :type        ["object"],
                                                                                 :properties  {:creditor {:description "ID of the [creditor](#whitelabel-partner-endpoints-creditors) that owns this bank account.",
                                                                                                          :example     "CR123",
                                                                                                          :type        ["string"]}}}},
                                   :links       [{:title        "Create a creditor bank account",
                                                  :description  "Creates a new creditor bank account object.",
                                                  :href         "/creditor_bank_accounts",
                                                  :method       "POST",
                                                  :rel          "create",
                                                  :schema       {:type                 ["object"],
                                                                 :properties           {:branch_code                   {:$ref "#/definitions/creditor_bank_account/definitions/branch_code"},
                                                                                        :currency                      {:$ref "#/definitions/creditor_bank_account/definitions/currency"},
                                                                                        :country_code                  {:$ref "#/definitions/creditor_bank_account/definitions/country_code"},
                                                                                        :bank_code                     {:$ref "#/definitions/creditor_bank_account/definitions/bank_code"},
                                                                                        :account_number                {:$ref "#/definitions/creditor_bank_account/definitions/account_number"},
                                                                                        :account_holder_name           {:$ref "#/definitions/creditor_bank_account/definitions/account_holder_name"},
                                                                                        :iban                          {:$ref "#/definitions/creditor_bank_account/definitions/iban"},
                                                                                        :set_as_default_payout_account {:$ref "#/definitions/creditor_bank_account/definitions/set_as_default_payout_account"},
                                                                                        :metadata                      {:$ref "#/definitions/customer/definitions/metadata"},
                                                                                        :links                         {:description          "",
                                                                                                                        :type                 ["object"],
                                                                                                                        :properties           {:creditor {:description "ID of the [creditor](#whitelabel-partner-endpoints-creditors) that owns this bank account.",
                                                                                                                                                          :example     "CR123",
                                                                                                                                                          :type        ["string"]}},
                                                                                                                        :required             ["creditor"],
                                                                                                                        :additionalProperties false}},
                                                                 :required             ["account_holder_name" "links"],
                                                                 :additionalProperties false},
                                                  :targetSchema {:$ref "#/definitions/creditor_bank_account/definitions/single_resource_response"},
                                                  :example      "POST https://api.gocardless.com/creditor_bank_accounts HTTP/1.1\n{\n  \"creditor_bank_accounts\": {\n    \"account_number\": \"55779911\",\n    \"branch_code\": \"200000\",\n    \"country_code\": \"GB\",\n    \"set_as_default_payout_account\": true,\n    \"account_holder_name\": \"Nude Wines\",\n    \"links\": {\n      \"creditor\": \"CR123\"\n    }\n  }\n}\n\nHTTP/1.1 201 (Created)\nLocation: /creditor_bank_accounts/BA123\n{\n  \"creditor_bank_accounts\": {\n    \"id\": \"BA123\",\n    \"created_at\": \"2014-05-27T12:43:17.000Z\",\n    \"account_holder_name\": \"Nude Wines\",\n    \"account_number_ending\": \"11\",\n    \"country_code\": \"GB\",\n    \"currency\": \"GBP\",\n    \"bank_name\": \"BARCLAYS BANK PLC\",\n    \"enabled\": true,\n    \"links\": {\n      \"creditor\": \"CR123\"\n    }\n  }\n}\n"}
                                                 {:title        "List creditor bank accounts",
                                                  :description  "Returns a [cursor-paginated](#overview-cursor-pagination) list of your creditor bank accounts.",
                                                  :href         "/creditor_bank_accounts",
                                                  :method       "GET",
                                                  :rel          "instances",
                                                  :schema       {:type                 ["object"],
                                                                 :properties
                                                                                       {:creditor {:$ref "#/definitions/creditor/definitions/identity"},
                                                                                        :after    {:type        ["string"],
                                                                                                   :description "Cursor pointing to the start of the desired set."},
                                                                                        :before   {:type        ["string"],
                                                                                                   :description "Cursor pointing to the end of the desired set."},
                                                                                        :limit    {:type        ["integer" "string"],
                                                                                                   :description "Number of records to return."},
                                                                                        :enabled  {:anyOf       [{:enum ["true" "false"]} {:type ["boolean"]}],
                                                                                                   :description "Get enabled or disabled creditor bank accounts."}},
                                                                 :additionalProperties false},
                                                  :targetSchema {:$ref "#/definitions/creditor_bank_account/definitions/multi_resource_response"},
                                                  :example      "GET https://api.gocardless.com/creditor_bank_accounts HTTP/1.1\n\nHTTP/1.1 200 (OK)\n{\n  \"meta\": {\n    \"cursors\": {\n      \"before\": null,\n      \"after\": \"BA123\",\n    },\n    \"limit\": 50\n  },\n  \"creditor_bank_accounts\":[{\n    \"id\": \"BA123\",\n    \"created_at\": \"2014-05-27T12:43:17.000Z\",\n    \"account_holder_name\": \"Nude Wines\",\n    \"account_number_ending\": \"11\",\n    \"country_code\": \"GB\",\n    \"currency\": \"GBP\",\n    \"bank_name\": \"BARCLAYS BANK PLC\",\n    \"enabled\": true,\n    \"links\": {\n      \"creditor\": \"CR123\"\n    }\n  }, {\n  ...\n  }]\n}\n"}
                                                 {:title        "Get a single creditor bank account",
                                                  :description  "Retrieves the details of an existing creditor bank account.",
                                                  :href         "/creditor_bank_accounts/{(%23%2Fdefinitions%2Fcreditor_bank_account%2Fdefinitions%2Fidentity)}",
                                                  :method       "GET",
                                                  :rel          "self",
                                                  :targetSchema {:$ref "#/definitions/creditor_bank_account/definitions/single_resource_response"},
                                                  :example      "GET https://api.gocardless.com/creditor_bank_accounts/BA123 HTTP/1.1\n\nHTTP/1.1 200 (OK)\n{\n  \"creditor_bank_accounts\": {\n    \"id\": \"BA123\",\n    \"created_at\": \"2014-05-27T12:43:17.000Z\",\n    \"account_holder_name\": \"Nude Wines\",\n    \"account_number_ending\": \"11\",\n    \"country_code\": \"GB\",\n    \"currency\": \"GBP\",\n    \"bank_name\": \"BARCLAYS BANK PLC\",\n    \"enabled\": true,\n    \"links\": {\n      \"creditor\": \"CR123\"\n    }\n  }\n}\n"}
                                                 {:title        "Disable a creditor bank account",
                                                  :description  "Immediately disables the bank account, no money can be paid out to a disabled account.\n\nThis will return a `disable_failed` error if the bank account has already been disabled.\n\nA disabled bank account can be re-enabled by creating a new bank account resource with the same details.",
                                                  :href         "/creditor_bank_accounts/{(%23%2Fdefinitions%2Fcreditor_bank_account%2Fdefinitions%2Fidentity)}/actions/disable",
                                                  :method       "POST",
                                                  :rel          "disable",
                                                  :targetSchema {:$ref "#/definitions/creditor_bank_account/definitions/single_resource_response"},
                                                  :example      "POST https://api.gocardless.com/creditor_bank_accounts/BA123/actions/disable HTTP/1.1\n\nHTTP/1.1 200 (OK)\n{\n  \"creditor_bank_accounts\": {\n    \"id\": \"BA123\",\n    \"created_at\": \"2014-05-27T12:43:17.000Z\",\n    \"account_holder_name\": \"Nude Wines\",\n    \"account_number_ending\": \"11\",\n    \"country_code\": \"GB\",\n    \"currency\": \"GBP\",\n    \"bank_name\": \"BARCLAYS BANK PLC\",\n    \"enabled\": false,\n    \"links\": {\n      \"creditor\": \"CR123\"\n    }\n  }\n}\n"}],
                                   :properties  {:bank_name             {:$ref "#/definitions/creditor_bank_account/definitions/bank_name"},
                                                 :currency              {:$ref "#/definitions/creditor_bank_account/definitions/currency"},
                                                 :country_code          {:$ref "#/definitions/creditor_bank_account/definitions/country_code"},
                                                 :id                    {:$ref "#/definitions/creditor_bank_account/definitions/id"},
                                                 :account_holder_name   {:$ref "#/definitions/creditor_bank_account/definitions/account_holder_name"},
                                                 :account_number_ending {:$ref "#/definitions/creditor_bank_account/definitions/account_number_ending"},
                                                 :enabled               {:$ref "#/definitions/creditor_bank_account/definitions/enabled"},
                                                 :metadata              {:$ref "#/definitions/customer/definitions/metadata"},
                                                 :created_at            {:$ref "#/definitions/creditor_bank_account/definitions/created_at"},
                                                 :links                 {:$ref "#/definitions/creditor_bank_account/definitions/links"}},
                                   :type        ["object"]}},
   :gocardless_version "2015-07-06",
   :type               ["object"],
   :title              "GoCardless Pro API",
   :id                 "gocardless-pro",
   :$schema            "https://developer.gocardless.com/hyper-schema.json",
   :links              [{:href "https://api.gocardless.com", :rel "self"}
                        {:href "https://api-sandbox.gocardless.com", :rel "self"}]})